using System.ComponentModel;
using System.ComponentModel.Design;
using System.Drawing.Design;

using KLib.TypeConverters;
using C462.Shared;

using BasicMeasurements;
using LDL.Haptics;

using OrderedPropertyGrid;

namespace LDL
{
    [TypeConverter(typeof(SortableTypeConverter))]
    public class LDLMeasurementSettings : BasicMeasurementConfiguration
    {
        [Category("Appearance")]
        public string Title { get; set; }

        [Category("Appearance")]
        [Editor(typeof(MultilineStringEditor), typeof(UITypeEditor))]
        public string Prompt { get; set; }

        [Category("Appearance")]
        public int PromptFontSize { get; set; }

        [Category("Sequence")]
        [Description("Ears to test")]
        [DisplayName("Ears")]
        public Audiograms.TestEar TestEar { get; set; }

        [Category("Sequence")]
        [Description("Test frequencies")]
        [DisplayName("Frequencies")]
        public float[] TestFrequencies { get; set; }

        [Category("Sequence")]
        [Description("Number of times to test each ear/frequency combo")]
        [DisplayName("Num repeats")]
        public int NumRepeats { get; set; }

        [Category("Bookkeeping")]
        [Description("Merge data generated by this audiogram with the existing data on the tablet")]
        [PropertyOrder(0)]
        public bool Merge { set; get; }

        [Category("Bookkeeping")]
        [PropertyOrder(1)]
        public bool LogSliderTracks { set; get; }

        [Category("Stimulus")]
        [Description("Bandwidth (octaves)")]
        [PropertyOrder(0)]
        public float Bandwidth { set; get; }

        [Category("Stimulus")]
        [Description("Duration of tone (ms)")]
        [PropertyOrder(1)]
        public float ToneDuration { set; get; }

        [Category("Stimulus")]
        [Description("Delay of tone (ms)")]
        [PropertyOrder(2)]
        public float ToneDelay { set; get; }

        [Category("Stimulus")]
        [Description("Pip interval (ms)")]
        [DisplayName("Pip interval")]
        [PropertyOrder(3)]
        public float ISI_ms { set; get; }

        [Category("Stimulus")]
        [Description("Ramp applied to tones (ms)")]
        [PropertyOrder(4)]
        public float Ramp { set; get; }

        [Category("Stimulus")]
        [Description("Minimum level")]
        [DisplayName("Min level")]
        [PropertyOrder(5)]
        public float MinLevel { set; get; }

        [Category("Stimulus")]
        [Description("Level units")]
        [PropertyOrder(6)]
        public LevelUnits LevelUnits { set; get; }

        [Category("Stimulus")]
        [Description("FM depth (percent)")]
        [DisplayName("FM depth")]
        [PropertyOrder(7)]
        public float ModDepth_pct { set; get; }

        [Category("Stimulus")]
        [DisplayName("Haptic")]
        [PropertyOrder(11)]
        public HapticStimulus HapticStimulus { set; get; }

        public LDLMeasurementSettings() : base()
        {
            Title = "How loud does it sound?";

            TestEar = Audiograms.TestEar.Both;
            TestFrequencies = new float[] { 1000, 2000, 4000 };

            Merge = true;
            LogSliderTracks = false;

            Ramp = 5f;
            ToneDelay = 0;
            ToneDuration = 200;
            Bandwidth = 0;
            ISI_ms = 400;
            ModDepth_pct = 0;
            MinLevel = 10;
            LevelUnits = LevelUnits.dB_SPL;
            NumRepeats = 3;

            Prompt = "Move sliders until sound is uncomfortable";
            PromptFontSize = 72;

            HapticStimulus = new HapticStimulus();
        }
    }
}
